config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  #components
  mount Isaac::Engine => "/isaac", as: 'isaac'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :isaac_tests, class_name: Isaac::Test, foreign_key: :author_id
  has_many :isaac_metrics, class_name: Isaac::Metric, foreign_key: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def main_navigation
    render_navigation renderer: :bootstrap do |primary|
      primary.dom_class = 'nav navbar-nav'
      primary.selected_class = 'active'

      primary.item :key_1_1, t('navbar.isaac'), isaac.root_path, class: 'item'
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
head
  title Quiz
  =stylesheet_link_tag    'application',  media: 'all', 'data-turbolinks-track' => true
  =javascript_include_tag 'application', 'data-turbolinks-track' => true
  =csrf_meta_tags
body
  nav.navbar.navbar-inverse
    .container-fluid
      .navbar-header
        =link_to t('navbar.brand'), main_app.root_path, class: 'navbar-brand'
      .collapse.navbar-collapse
        -if signed_in?
          =main_navigation
          ul.nav.navbar-nav.navbar-right
            li
              =link_to t('devise.sessions.buttons.sign_out'), main_app.destroy_user_session_path, method: :delete
  .container
    =yield

app/views/welcome/_guest_page.html.slim
.page-header
  h1
    =t('application_name')
    small &nbsplorem ipsum
.container
  .row.row-eq-height
    .col-sm-5.col-md-5
      =simple_form_for(:user, url: new_session_path(:user)) do |f|
        =f.input :email
        =f.input :password
        =f.submit t('devise.sessions.buttons.sign_in'), class: 'btn btn-primary'
    .col-sm-5.col-md-2
      h2.bold.text-center
        =t('divider')
    .col-sm-5.col-md-5.text-center
      = link_to t('devise.registrations.buttons.sign_up'), new_user_registration_path,
                class: 'btn btn-lg btn-success full-width'

app/views/welcome/_user_page.html.slim
.page-header
  h2 User index page

app/views/welcome/index.html.slim
-if signed_in?
  =render 'user_page'
-else
  =render 'guest_page'