components/isaac/config/routes.rb
Isaac::Engine.routes.draw do
  root to: 'tests#index'
  resources :tests do
    resources :results
  end
  resources :metrics
end

components/isaac/app/models/isaac/answer.rb
module Isaac
  class Answer < ActiveRecord::Base
    belongs_to :isaac_question, class_name: Isaac::Question, foreign_key: :isaac_question_id
  end
end

components/isaac/app/models/isaac/metric.rb
module Isaac
  class Metric < ActiveRecord::Base
    belongs_to :author, class_name: Isaac.author_class
    has_many :isaac_metric_tests, class_name: Isaac::MetricTest, foreign_key: :isaac_metric_id
    has_many :isaac_tests, through: :isaac_metric_tests, class_name: Isaac::Test, foreign_key: :isaac_metric_id
    has_many :isaac_metric_graduations, class_name: Isaac::MetricGraduation, foreign_key: :isaac_metric_id
    has_many :isaac_questions, class_name: Isaac::Question, foreign_key: :isaac_metric_id

    accepts_nested_attributes_for :isaac_metric_graduations
    accepts_nested_attributes_for :isaac_questions

    def self.author_class
      Isaac.author_class.constantize
    end
  end
end

components/isaac/app/models/isaac/metric_graduation.rb
module Isaac
  class MetricGraduation < ActiveRecord::Base
    belongs_to :isaac_metric, class_name: Isaac::Metric, foreign_key: :isaac_metric_id
  end
end

components/isaac/app/models/isaac/metric_test.rb
module Isaac
  class MetricTest < ActiveRecord::Base
    belongs_to :isaac_metric, foreign_key: :isaac_metric_id, class_name: Isaac::Metric
    belongs_to :isaac_test, foreign_key: :isaac_test_id, class_name: Isaac::Metric
  end
end

components/isaac/app/models/isaac/question.rb
module Isaac
  class Question < ActiveRecord::Base
    belongs_to :isaac_metric, class_name: Isaac::Metric, foreign_key: :isaac_metric_id
    has_many :isaac_answers, class_name: Isaac::Answer, foreign_key: :isaac_question_id

    accepts_nested_attributes_for :isaac_answers

  end
end

components/isaac/app/models/isaac/result.rb
module Isaac
  class Result < ActiveRecord::Base
    belongs_to :isaac_test, class_name: Isaac::Test, foreign_key: :isaac_test_id
  end
end

components/isaac/app/models/isaac/test.rb
module Isaac
  class Test < ActiveRecord::Base
    belongs_to :author, class_name: Isaac.author_class
    has_many :isaac_metric_tests, class_name: Isaac::MetricTest, foreign_key: :isaac_test_id
    has_many :isaac_metrics, through: :isaac_metric_tests, class_name: Isaac::Metric
    has_many :isaac_results, class_name: Isaac::Result, foreign_key: :isaac_test_id

    accepts_nested_attributes_for :isaac_metric_tests

    validates :author_id, presence: true

    def self.author_class
      Isaac.author_class.constantize
    end
  end
end

components/isaac/app/controllers/isaac/application_controller.rb
module Isaac
  class ApplicationController < ::ApplicationController
    helper Isaac::NavigationHelper

    def current_author
      send(Isaac.current_author_helper)
    end

    helper_method :current_author
  end
end

components/isaac/app/controllers/isaac/metrics_controller.rb
module Isaac
  class MetricsController < ApplicationController
    def index
      @metrics = Isaac::Metric.all
    end

    def show
      @metric = Isaac::Metric.find(params[:id])
    end

    def new
      @metric = Isaac::Metric.new
    end

    def create
      metric = Isaac::Metric.new(metric_params)
      if metric.save
        redirect_to metrics_path
      else
        @metric = metric
        render :new
      end
    end

    def edit
      @metric = Isaac::Metric.find(params[:id])
    end

    def update
      metric = Isaac::Metric.find(params[:id])
      if metric.update(metric_params)
        redirect_to metrics_path
      else
        @metric = metric
        render :edit
      end
    end

    def destroy
      @metric = Isaac::Metric.find(params[:id])
      if @metric.destroy
        redirect_to metrics_path
      else
        redirect_to metrics_path, notice: 'destroy fail'
      end
    end

    private

    def metric_params
      params.require(:metric).
          permit(:name, :description, :author_id,
                 isaac_metric_graduations_attributes: [:id, :name, :description, :_destroy, :min_value, :max_value],
                 isaac_questions_attributes: [:id, :body, :_destroy,
                                              isaac_answers_attributes: [:id, :body, :value, :_destroy]]).
          merge(author_id: current_author.id)
    end
  end
end

components/isaac/app/controllers/isaac/results_controller.rb
require 'pry'
module Isaac
  class ResultsController < ApplicationController
    def index
      @results = Isaac::Result.all
    end

    def show
      @result = Isaac::Result.find(params[:id])
      @report = Isaac::Result::ReportBuilder.new(@result).call
    end

    def new
      @test = Isaac::Test.find(params[:test_id])
      @result = @test.isaac_results.build
      @test_metrics = @test.isaac_metrics.includes(isaac_questions: [:isaac_answers])
    end

    def create
      result = Isaac::Test.find(params[:test_id]).isaac_results.new(answers: result_params)
      if result.save
        redirect_to test_result_path(params[:test_id], result)
      else
        @reslut = result
        render :new
      end
    end

    def destroy

    end

    private

    def result_params
      params.require(:result_form).permit!.to_json
    end
  end
end

components/isaac/app/controllers/isaac/tests_controller.rb
module Isaac
  class TestsController < ApplicationController
    def index
      @tests = Isaac::Test.all
    end

    def new
      @test = Isaac::Test.new
    end

    def create
      Isaac::Test.new(test_params) do |test|
        if test.save
          redirect_to root_path
        else
          @test = test
          render :new
        end
      end
    end

    def edit
      @test = Isaac::Test.find(params[:id])
    end

    def update
      @test = Isaac::Test.find(params[:id])
      if @test.update(test_params)
        redirect_to tests_path
      else
        render :edit, notice: 'fail update'
      end
    end

    def destroy
      @test = Isaac::Test.find(params[:id])
      if @test.destroy
        redirect_to tests_path
      else
        redirect_to tests_path, notice: 'fail destroy'
      end
    end

    private

    def test_params
      params.require(:test).permit(:name, :description, :author_id,
                                   isaac_metric_tests_attributes: [:id, :isaac_metric_id, :_destroy])
          .merge(author_id: current_author.id)
    end
  end
end

components/isaac/app/helpers/isaac/application_helper.rb
module Isaac
  module ApplicationHelper
  end
end

components/isaac/app/helpers/isaac/navigation_helper.rb
module Isaac
  module NavigationHelper
    def isaac_navigation
      render_navigation renderer: :bootstrap do |primary|
        primary.dom_class = 'nav nav-tabs'
        primary.selected_class = 'active'

        primary.item :key_1_1, t('navbar.tests'), isaac.tests_path, class: 'item'
        primary.item :key_1_2, t('navbar.metrics'), isaac.metrics_path, class: 'item'
      end
    end
  end
end

components/isaac/app/helpers/isaac/test_helper.rb
module Isaac
  module TestHelper
    def metrics_collection
      Isaac::Metric.all
    end
  end
end

components/isaac/app/views/isaac/metrics/_form.html.slim
=simple_form_for @metric do |f|
  =f.input :name
  .row
    .col-md-4
      #metric-graduations
        h3 Metric Graduations
        =f.simple_fields_for :isaac_metric_graduations do |isaac_metric_graduation|
          =render 'isaac_metric_graduation_fields', f: isaac_metric_graduation
      .links
        = link_to_add_association 'add graduation', f, :isaac_metric_graduations
    .col-md-8
      #metric-questions
        h3 Metric Questions
        =f.simple_fields_for :isaac_questions do |isaac_question|
          =render 'isaac_question_fields', f: isaac_question
      .links
        = link_to_add_association 'add question', f, :isaac_questions
  =f.submit 'save'

components/isaac/app/views/isaac/metrics/_isaac_answer_fields.html.slim
.nested-fields
  =f.input :body
  =f.input :value
  =link_to_remove_association 'remove answer', f

components/isaac/app/views/isaac/metrics/_isaac_metric_graduation_fields.html.slim
.nested-fields
  =f.input :name
  =f.input :min_value
  =f.input :max_value
  =f.input :description
  =link_to_remove_association 'remove graduation', f

components/isaac/app/views/isaac/metrics/_isaac_question_fields.html.slim
.nested-fields
  .row
    .col-md-6
      =f.input :body
    .col-md-6
      #question-answers
        h4 Answers
        =f.simple_fields_for :isaac_answers do |isaac_answer|
          =render 'isaac_answer_fields', f: isaac_answer
        .links
          = link_to_add_association 'add answer', f, :isaac_answers
    =link_to_remove_association 'remove question', f

components/isaac/app/views/isaac/metrics/edit.html.slim
=render partial: 'isaac/shared/navbar'
h2 Edit test
=render partial: 'form'

components/isaac/app/views/isaac/metrics/index.html.slim
=render partial: 'isaac/shared/navbar'
h2 Metric index page

.container
  =link_to 'new', new_metric_path, class: 'btn btn-default'
  table.table
    thead
      th name
      th description
      th author
      th actions
    tbody
      -@metrics.each do |metric|
        tr
          td =metric.name
          td =metric.description
          td =metric.author.email
          td
            .btn-group
              =link_to 'show', metric_path(metric), class: 'btn btn-default'
              =link_to 'edit', edit_metric_path(metric), class: 'btn btn-default'
              =link_to 'destroy', metric_path(metric), method: :delete, class: 'btn btn-default'

components/isaac/app/views/isaac/metrics/new.html.slim
=render partial: 'isaac/shared/navbar'
h2 New metric
=render partial: 'form'

components/isaac/app/views/isaac/results/new.html.slim
h2 =@test.name
=simple_form_for :result_form, url: test_results_path(@test, @result) do |f|
  -@test_metrics.each do |tm|
    =f.simple_fields_for :"metric_id_#{tm.id}" do |mf|
      -tm.isaac_questions.each do |iq|
        =mf.label iq.body
        =mf.input :"question_id_#{iq.id}", label: false, as: :radio_buttons,
                 collection: iq.isaac_answers.map {|a| [a.body, a.id]}
  =f.submit 'save'

components/isaac/app/views/isaac/results/show.html.slim
h2 Result

=@report

components/isaac/app/views/isaac/shared/_navbar.html.slim
=isaac_navigation